 use toil;
 describe toil;
 CREATE TABLE toilUser(
user_id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
email_id VARCHAR(70) NOT NULL,
f_name VARCHAR(40),
l_name VARCHAR(40),
company VARCHAR(40),
phoneNumber VARCHAR(40),
isActive TINYINT(1) UNSIGNED  NOT NULL DEFAULT 1,
passwd VARCHAR(32) NOT NULL,
isadmin TINYINT(1) UNSIGNED  NOT NULL DEFAULT 1,
admin_id INT(10) UNSIGNED,
CONSTRAINT FK_ADMINID_tbl_toilUser FOREIGN KEY(admin_id)
        REFERENCES toilUser(user_id),
INDEX (email_id(10))
)
select * from toilUser;
 INSERT INTO toilUser (email_id,f_name,l_name,company,phoneNumber,isActive,passwd,isadmin,admin_id) 
 VALUES ('shilbbbpa@yahoo.com','Shijjjlpa','G','adobe','987jjj7876',1,'admin',1,3);
 
 CREATE TABLE job_type(
type_id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
type VARCHAR(40) NOT NULL,
type_desc VARCHAR(150),
INDEX  icat (type(10)),
FULLTEXT fcat (type)
)
select * from job_duration;
INSERT INTO job_type (type,type_desc) 
 VALUES ('Contract','Contract');
 INSERT INTO job_type (type,type_desc)  VALUES ('Permanent','Permanent');
 
 
 --
 CREATE TABLE job_industry(
industry_id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(40) NOT NULL,
INDEX  icat (name(10)),
FULLTEXT fcat (name)
)
INSERT INTO job_industry (name)  VALUES ('Aerospace & Defense'),
('Automotive'),
('Comms & High Tec '),
('Comms & High Tec - Mobile'),
('Comms & High Tec - Web'),
('Consumer Goods - Electrical Equipment'),
('Consumer Goods - Food & Beverage'),
('Consumer Goods - Home & Personal Care'),
('Consumer Goods - Other'),
('Consumer Goods - Tobacco'),
('Financial Services'),
('Healthcare '),
('Industrial Goods '),
('Logistics'),
('Pharmaceuticals'),
('Resources - Farming & Agriculture'),
('Resources - Metals & Minerals'),
('Resources - Mining'),
('Resources - Oil & Gas'),
('Waste Management');

select * from job_table
-----
 CREATE TABLE job_currency(
currency_id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(40) NOT NULL,
INDEX  icat (name(10)),
FULLTEXT fcat (name)
)
INSERT INTO job_currency (name)  VALUES 
('USD - US Dollars'),
('GBP - British Pounds'),
('EUR - Euros'),
('CHF - Swiss Francs'),
('INR - Indian Rupees'),
('AUD - Australian Dollars'),
('AED - UAE Dirhams'),
('HKD - Hong Kong Dollars'),
('CNY - Chinese Yuan Renminbi'),
('RUB - Russian Rubles'),
('JPY - Japanese Yen')
====
CREATE TABLE job_duration(
duration_id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
duration VARCHAR(40) NOT NULL,
INDEX  icat (duration(10)),
FULLTEXT fcat (duration)
)

INSERT INTO job_duration (duration)  VALUES 
('<1 Month'),
('1-2 Months'),
('3-6 Months'),
('7-9 Months'),
('>9 Months')
---
CREATE TABLE language(
language_id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
language VARCHAR(40) NOT NULL,
INDEX  icat (language(10)),
FULLTEXT fcat (language)
)
INSERT INTO language (language)  VALUES 
('English'),
('German'),
('French'),
('Italian'),
('Spanish'),
('Mandarin'),
('Japanese'),
('Dutch'),
('Russian'),
('Hindi'),
('Urdu'),
('Arabic'),
('Portugese'),
('Bengali'),
('Punjabi')
------
CREATE TABLE country(
country_id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
INDEX  icat (name(10)),
FULLTEXT fcat (name)
)
INSERT into country (name) values
('United Kingdom'),
('United States of America'),
('Germany'),
('Switzerland'),
('France'),
('Australia'),
('India'),
('United Arab Emirates'),
('China'),
('Russia'),
('Japan'),
('Afghanistan'),
('Åland Islands (Finland)'),
('Albania'),
('Algeria'),
('American Samoa (USA)'),
('Andorra'),
('Angola'),
('Anguilla (UK)'),
('Antigua and Barbuda'),
('Argentina'),
('Armenia'),
('Aruba (Netherlands)'),
('Australia'),
('Austria'),
('Azerbaijan'),
('Bahamas'),
('Bahrain'),
('Bangladesh'),
('Barbados'),
('Belarus'),
('Belgium'),
('Belize'),
('Benin'),
('Bermuda (UK)'),
('Bhutan'),
('Bolivia'),
('Bosnia and Herzegovina'),
('Botswana'),
('Brazil'),
('British Indian Ocean Territory (UK)'),
('British Virgin Islands (UK)'),
('Brunei'),
('Bulgaria'),
('Burkina Faso'),
('Burundi'),
('Cabo Verde'),
('Cambodia'),
('Cameroon'),
('Canada'),
('Caribbean Netherlands (Netherlands)'),
('Cayman Islands (UK)'),
('Central African Republic'),
('Chad'),
('Chile'),
('China'),
('Christmas Island (Australia)'),
('Cocos (Keeling) Islands (Australia)'),
('Colombia'),
('Comoros'),
('Congo, Republic of the'),
('Congo, Democratic Republic of the'),
('Cook Islands (New Zealand)'),
('Costa Rica'),
('Cote d''Ivoire'),
('Croatia'),
('Cuba'),
('Curaçao (Netherlands)'),
('Cyprus'),
('Czech Republic'),
('Denmark'),
('Djibouti'),
('Dominica'),
('Dominican Republic'),
('Ecuador'),
('Egypt'),
('El Salvador'),
('Equatorial Guinea'),
('Eritrea'),
('Estonia'),
('Ethiopia'),
('Falkland Islands (UK)'),
('Faroe Islands (Denmark)'),
('Fiji'),
('Finland'),
('France'),
('French Guiana (France)'),
('French Polynesia (France)'),
('Gabon'),
('Gambia'),
('Georgia'),
('Germany'),
('Ghana'),
('Gibraltar (UK)'),
('Greece'),
('Greenland (Denmark)'),
('Grenada'),
('Guadeloupe (France)'),
('Guam (USA)'),
('Guatemala'),
('Guernsey (UK)'),
('Guinea'),
('Guinea-Bissau'),
('Guyana'),
('Haiti'),
('Honduras'),
('Hong Kong (China)'),
('Hungary'),
('Iceland'),
('India'),
('Indonesia'),
('International Monetary Fund (IMF)'),
('Iran'),
('Iraq'),
('Ireland'),
('Isle of Man (UK)'),
('Israel'),
('Italy'),
('Jamaica'),
('Japan'),
('Jersey (UK)'),
('Jordan'),
('Kazakhstan'),
('Kenya'),
('Kiribati'),
('Kosovo'),
('Kuwait'),
('Kyrgyzstan'),
('Laos'),
('Latvia'),
('Lebanon'),
('Lesotho'),
('Liberia'),
('Libya'),
('Liechtenstein'),
('Lithuania'),
('Luxembourg'),
('Macau (China)'),
('Macedonia'),
('Madagascar'),
('Malawi'),
('Malaysia'),
('Maldives'),
('Mali'),
('Malta'),
('Marshall Islands'),
('Martinique (France)'),
('Mauritania'),
('Mauritius'),
('Mayotte (France)'),
('Mexico'),
('Micronesia'),
('Moldova'),
('Monaco'),
('Mongolia'),
('Montenegro'),
('Montserrat (UK)'),
('Morocco'),
('Mozambique'),
('Myanmar'),
('Namibia'),
('Nauru'),
('Nepal'),
('Netherlands'),
('New Caledonia (France)'),
('New Zealand'),
('Nicaragua'),
('Niger'),
('Nigeria'),
('Niue (New Zealand)'),
('Norfolk Island (Australia)'),
('North Korea'),
('Northern Mariana Islands (USA)'),
('Norway'),
('Oman'),
('Pakistan'),
('Palau'),
('Palestine'),
('Panama'),
('Papua New Guinea'),
('Paraguay'),
('Peru'),
('Philippines'),
('Pitcairn Islands (UK)'),
('Poland'),
('Portugal'),
('Puerto Rico (USA)'),
('Qatar'),
('Reunion (France)'),
('Romania'),
('Russia'),
('Rwanda'),
('Saint Barthélemy (France)'),
('Saint Helena (UK)'),
('Saint Kitts and Nevis'),
('Saint Lucia'),
('Saint Martin (France)'),
('Saint Pierre and Miquelon (France)'),
('Saint Vincent and the Grenadines'),
('Samoa'),
('San Marino'),
('Sao Tome and Principe'),
('Saudi Arabia'),
('Senegal'),
('Serbia'),
('Seychelles'),
('Sierra Leone'),
('Singapore'),
('Sint Maarten (Netherlands)'),
('Slovakia'),
('Slovenia'),
('Solomon Islands'),
('Somalia'),
('South Africa'),
('South Korea'),
('South Sudan'),
('Spain'),
('Sri Lanka'),
('Sudan'),
('Suriname'),
('Svalbard and Jan Mayen (Norway)'),
('Swaziland'),
('Sweden'),
('Switzerland'),
('Syria'),
('Taiwan'),
('Tajikistan'),
('Tanzania'),
('Thailand'),
('Timor-Leste'),
('Togo'),
('Tokelau (New Zealand)'),
('Tonga'),
('Trinidad and Tobago'),
('Tunisia'),
('Turkey'),
('Turkmenistan'),
('Turks and Caicos Islands (UK)'),
('Tuvalu'),
('Uganda'),
('Ukraine'),
('United Arab Emirates'),
('United Kingdom'),
('United States of America'),
('Uruguay'),
('US Virgin Islands (USA)'),
('Uzbekistan'),
('Vanuatu'),
('Vatican City (Holy See)'),
('Venezuela'),
('Vietnam'),
('Wallis and Futuna Islands (France)'),
('Yemen'),
('Zambia'),
('Zimbabwe')
------------
CREATE TABLE job_table(
job_id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
job_title VARCHAR(250) NOT NULL,
job_type INT(10) UNSIGNED NOT NULL,
job_desc TEXT NOT NULL,
industry_id INT(10) UNSIGNED NOT NULL,
ind_wtg TINYINT(2) UNSIGNED,
salary DECIMAL(10,2),
sal_wtg TINYINT(2) UNSIGNED,
currency_id INT(10) UNSIGNED NOT NULL,
duration_id INT(10) UNSIGNED NOT NULL,
country_id INT(10) UNSIGNED NOT NULL,
country_wtg TINYINT(2) UNSIGNED,
city VARCHAR(100) NOT NULL,
istravel TINYINT(1) UNSIGNED  NOT NULL DEFAULT 1,
trvl_wtg TINYINT(2) UNSIGNED,
lang_id INT(10) UNSIGNED NOT NULL,
lang_wtg TINYINT(2) UNSIGNED,
start_date DATE NOT NULL,
srtdt_wtg TINYINT(2) UNSIGNED,
created_by INT(10) UNSIGNED NOT NULL,
FULLTEXT job_key (job_title)
)
----
 INSERT INTO job_table (job_title,job_type,job_desc,industry_id,ind_wtg,salary,sal_wtg,currency_id,duration_id,
 country_id,country_wtg,city,istravel,trvl_wtg,lang_id,lang_wtg,start_date,srtdt_wtg,created_by)
 VALUES ('Developer',2,'Description hfdgdsfh',2,2,3000,2,2,2,2,1,'London',1,2,2,2,STR_TO_DATE('10/11/2016', '%d/%m/%Y'),2,2);
 
 INSERT INTO job_table (job_title,job_type,job_desc,industry_id,ind_wtg,salary,sal_wtg,currency_id,duration_id,
 country_id,country_wtg,city,istravel,trvl_wtg,lang_id,lang_wtg,start_date,srtdt_wtg,created_by)
 VALUES ('Developer',2,'Description hfdgdsfh',2,2,3000,2,2,2,2,1,'London',1,2,2,2,'2016-11-30',2,2);
 
 INSERT INTO job_table (job_title,job_type,job_desc,industry_id,ind_wtg,salary,sal_wtg,currency_id,duration_id,country_id,country_wtg,city,istravel,trvl_wtg,lang_id,lang_wtg,start_date,srtdt_wtg,created_by) 
 VALUES('Big data','1','Big dataBig dataBig dataBig databig data','2','2','456','2','3','3','3','3','London','1','1','2','2','2015-12-24','3','3')
 select * from job_table
SELECT LAST_INSERT_ID();
-----

CREATE TABLE skill(
skill_id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
skill_name VARCHAR(100) NOT NULL,
INDEX  iskills (skill_name(10)),
FULLTEXT fskills (skill_name)
)
INSERT into skill (skill_name) values
('Basis-Basis'),
('Basis-Security (BC – SEC)'),
('Basis-Application Link Enabling (ALE)'),
('Basis-Remote Function Calls (RFC)'),
('Basis-Object Linking and Embedding (OLE)'),
('Basis-Common Program Interface Communications (CPI-C)'),
('Basis-Electronic Data Interchange (EDI)'),
('Basis-Customizing (BC-CUS)'),
('Basis-ABAP Programming and Runtime Environment (BC – ABA)'),
('Basis-Client Server Technology (BC – CST)'),
('Basis-Network Integration (BC – NET)'),
('Basis-Basis Services/ Communication Interfaces (BC – SRV)'),
('Basis-Computing Center Management System (BC – CCM)'),
('Basis-Upgrade General (BC – UPG)'),
('Basis-Change and Transport System (BC – CTS)'),
('Basis-Operating System Platform (BC – OP)'),
('Basis-Database Interface, database platforms (BC – DB)'),
('Basis-Front End Services (BC – FES)'),
('Basis-ABAP Workbench (BC – DWB)'),
('Basis-Documentation and Translation Tools (BC – DOC)'),
('Basis-Controls and Control Framework (BC – CI)'),
('Basis-Business Management (BC – BMT)'),
('Basis-Middleware (BC – MID)'),
('Basis-Computer Aided Test Tool (BC – CAT)'),
('Basis-Ready to Run R/3 (BC – BRR)'),
('Basis-Authorization System Monitoring with CCMS Workload Alert Monitor'),
('ABAP/4-ABAP/4'),
('ABAP/4-ABAP Workbench'),
('ABAP/4-Menu Painter'),
('ABAP/4-Screen Painter'),
('ABAP/4-Data Dictionary'),
('ABAP/4-SAP Script'),
('ABAP/4-Business Workflow (BC – WF)'),
('ABAP/4-ALE'),
('ABAP/4-EDI'),
('ABAP/4-Business Connector'),
('ABAP/4-Business Server Pages'),
('ABAP/4-Internet Application Server'),
('ABAP/4-Mercator Report Painter'),
('ABAP/4-ALV reporting'),
('ABAP/4-Report writer'),
('ABAP/4-Dialog Programming'),
('ABAP/4-Repository Information System'),
('ABAP/4-ABAP 0'),
('ABAP/4-IDOCS'),
('ABAP/4-LSMW'),
('ABAP/4-Smart forms'),
('ABAP/4-EBP'),
('ABAP/4-ASAP methodology'),
('SAP FI-SAP Finance'),
('SAP FI-General Ledger Accounting (FI – GL)'),
('SAP FI-Special Ledger (FI – SL)'),
('SAP FI-Extended Ledger'),
('SAP FI-Accounts Payable (FI- AP)'),
('SAP FI-Accounts Receivable (FI – AR)'),
('SAP FI-Asset Accounting (FI – AA)'),
('SAP FI-Bank Accounting'),
('SAP FI-Funds Management (FI – FM)'),
('SAP FI-Travel Management (FI-TM)'),
('SAP FI-Consolidation'),
('SAP CO-SAP Controlling'),
('SAP CO-Cost Centre Accounting (CO – CCA)'),
('SAP CO-Overhead Cost Controlling (CO – OM)'),
('SAP CO-Activity Based Coding (CO – ABC)'),
('SAP CO-Product Cost Controlling (CO – PC)'),
('SAP CO-Profitability Analysis (CO – PA)'),
('SAP CO-Material Ledger (CO – ML)'),
('SAP EC-SAP EC (Enterprise Controlling)'),
('SAP EC-Consolidation (EC – CS)'),
('SAP EC-Executive Information System (EC-EIS)'),
('SAP EC-Profit Center Accounting (EC – PCA)'),
('SAP EC-Business Planning and Budgeting'),
('SAP TR-SAP Treasury'),
('SAP TR-Cash Management (TR – CM)'),
('SAP TR-Loans Management (TR – LM)'),
('SAP TR-Market Risk Management (TR – MRM)'),
('SAP TR-Treasury Management (TR – TM)'),
('SAP TR-Funds Management (TR – FM)'),
('SAP TR-Information System'),
('SAP IM-SAP Investment Management'),
('SAP IM-Investment Programs'),
('SAP IM-Investment Measures (orders/products)'),
('SAP IM-Corporation Wide Budgeting'),
('SAP IM-Appropriation Requests'),
('SAP IM-Automatic Settlement of Fixed Assets'),
('SAP IM-Depreciation Forecast'),
('SAP IM-Information System'),
('SAP HR-SAP HR (Human Resource)'),
('SAP HR-Recruitment'),
('SAP HR-Personnel Administration'),
('SAP HR-Benefits Administration'),
('SAP HR-Compensation Management'),
('SAP HR-Personnel Development'),
('SAP HR-Organizational Management'),
('SAP HR-Travel Management'),
('SAP HR-Training and Events Management'),
('SAP HR-Personnel Planning'),
('SAP HR-Time Management'),
('SAP HR-Incentive'),
('SAP HR-Wages'),
('SAP HR-Workflow'),
('SAP HR-Payroll'),
('SAP HR-Internet Scenarios'),
('SAP HR-Information System'),
('SAP SD-SAP Sales and Distribution'),
('SAP SD-Master Data'),
('SAP SD-Sales'),
('SAP SD-Sales Support'),
('SAP SD-Sales Information System'),
('SAP SD-Billing'),
('SAP SD-Special Business Transactions'),
('SAP SD-Shipping'),
('SAP SD-Transportation'),
('SAP SD-Credit Control'),
('SAP SD-QM in SD'),
('SAP SD-Internet'),
('SAP SD-Foreign Trade'),
('SAP SD-Electronic Data Interchange'),
('SAP LIS-SAP Logistics Information System'),
('SAP LIS-Purchasing Information System'),
('SAP LIS-Sales Information System'),
('SAP LIS-Inventory Controlling'),
('SAP LIS-Retail Information System'),
('SAP LIS-Production Planning and Control Information System'),
('SAP LIS-Plant Maintenance Information System'),
('SAP LIS-Project Information System'),
('SAP MM-SAP Materials Management'),
('SAP MM-Purchasing'),
('SAP MM-Invoice Verification'),
('SAP MM-Logistics (General)'),
('SAP MM-Logistics Information System'),
('SAP MM-Inventory Management'),
('SAP MM-Inventory / Valuations'),
('SAP MM-Materials Planning'),
('SAP MM-Workflow'),
('SAP MM-External Services Management'),
('SAP MM-QM in MM'),
('SAP MM-Warehouse Management'),
('SAP PM-SAP Plant Maintenance'),
('SAP PM-Preventative Maintenance'),
('SAP PM-Maintenance Order Management'),
('SAP PM-Maintenance Projects'),
('SAP PM-Service Management'),
('SAP PM-Maintenance Planning'),
('SAP PM-Equipment and Technical Objects'),
('SAP PM-Structuring Technical Systems'),
('SAP PM-PM Processing'),
('SAP PM-Work Clearance Management'),
('SAP PM-Internet Scenarios'),
('SAP PM-Customizing'),
('SAP PM-Information System'),
('SAP PP-SAP Production Planning'),
('SAP PP-Make to Order (CR)'),
('SAP PP-Make to Order (PIR)'),
('SAP PP-Repetitive Manufacturing'),
('SAP PP-PP for Process Industries (PP – PI)'),
('SAP PP-PP – Processes'),
('SAP PP-Sales and Operations Planning'),
('SAP PP-Capacity requirements'),
('SAP PP-Master Planning'),
('SAP PP-KANBAN'),
('SAP PP-Production Orders'),
('SAP PP-Product Cost Planning'),
('SAP PP-Plant Data Collection'),
('SAP PP-Assembly Orders'),
('SAP PP-Information System'),
('SAP QM-SAP Quality Management'),
('SAP QM-Planning'),
('SAP QM-Inspections'),
('SAP QM-Notifications'),
('SAP QM-Control'),
('SAP QM-Certificates'),
('SAP QM-Test Equipment Management'),
('SAP QM-QM-IS'),
('SAP BW-SAP Business Warehousing'),
('SAP BW-Data Warehousing'),
('SAP BW-BI Suite – Business Explorer'),
('SAP BW-BI Platform'),
('SAP BW-ODS Structures'),
('SAP BW-Development Technologies'),
('SAP BW-Info Cube'),
('SAP BW-Design Build'),
('SAP CS-SAP Customer Service'),
('SAP CS-Service Processing'),
('SAP CS-Controlling'),
('SAP CS-Service Contracts'),
('SAP CS-Workflow in Customer Service'),
('SAP SMB-SAP SMB'),
('SAP CA-SAP Cross Application Components'),
('Workflow-SAP Business Workflow'),
('ALE-Application Link Enabling (ALE)'),
('SAP PS-SAP Project Systems'),
('SAP PS-Basic Data'),
('SAP PS-Operational Structures'),
('SAP PS-Project Planning'),
('SAP PS-Approval'),
('SAP PS-Information System'),
('SAP PS-Project Execution and Integration'),
('SAP PS-Work Breakdown Structure'),
('mySAP SRM-mySAP SRM (Supplier Relationship Management)'),
('mySAP SRM-Self Service Procurement'),
('mySAP SRM-Service Procurement'),
('mySAP SRM-Plan Driven Procurement'),
('mySAP SRM-Spend Analysis'),
('mySAP SRM-Strategic Sourcing'),
('mySAP SRM-Catalogue Content Management'),
('mySAP SEM-mySAP SEM'),
('mySAP SEM-Business Consolidation (SEM-BCS)'),
('mySAP SEM-Business Information Collection (SEM-BIC)'),
('mySAP SEM-Business Planning and Simulation (BW-BPS)'),
('mySAP SEM-Corporate Performance Monitor (SEM-CPM)'),
('mySAP SEM-Stakeholder Relationship Management (SEM-SRM)'),
('mySAP CRM-mySAP CRM (Customer Relationship Management)'),
('mySAP CRM-CRM Enterprise'),
('mySAP CRM-Field Applications'),
('mySAP CRM-Interaction Center'),
('mySAP CRM-E-Commerce'),
('mySAP CRM-Channel Management'),
('mySAP CRM-Industry Specific CRM'),
('mySAP CRM-Document Management'),
('mySAP CRM-Engineering Change Management'),
('mySAP CRM-Enterprise Content Management'),
('mySAP CRM-Classification'),
('mySAP CRM-Basic Data for Process Manufacturing'),
('SAP SCM-SAP Supply Chain Management'),
('SAP SCM-SCM Process and Business Scenarios'),
('SAP SCM-SAP Forecasting and Replenishment'),
('SAP SCM-SAP Advance Planning and Optimization (SAP – APO)'),
('SAP SCM-SAP – APO: Demand Planning (DP)'),
('SAP SCM-SAP – APO: Supply Network Planning (SNP)'),
('SAP SCM-SAP – APO: Vehicle Scheduling (VS)'),
('SAP SCM-SAP – APO: Transportation Planning (TP)'),
('SAP SCM-SAP – APO: Production Planning & Details Scheduling (PP/DS)'),
('SAP SCM-SAP Inventory Collaboration Hub (SAP – OCH)'),
('SAP SCM-SAP Event Management (SAP – EM)'),
('SAP SCM-Global Available to Promise (GATP)'),
('SAP SCM-APO-BI'),
('SAP SCM-SCM Basis'),
('SAP Netweaver-SAP Netweaver'),
('SAP Netweaver-SAP Master data Management'),
('SAP Netweaver-Information Integration'),
('SAP Netweaver-Portal Content'),
('SAP Netweaver-Process Integration'),
('SAP Netweaver-Knowledge Management'),
('SAP Netweaver-Life Cycle Management'),
('SAP Netweaver-SAP Business Intelligence'),
('SAP Netweaver-SAP Visual Composer'),
('SAP Netweaver-People Integration'),
('SAP Netweaver-Application Platform'),
('SAP Netweaver-SAP Web Application Server'),
('SAP Netweaver-SAP Business Information Warehouse'),
('SAP Netweaver-SAP Solution Manager'),
('SAP Netweaver-SAP Enterprise Portal'),
('SAP Netweaver-SAP Mobile Engine'),
('SAP Netweaver-Security'),
('SAP IS-SAP Industry Solutions'),
('SAP IS-Aerospace & Defense'),
('SAP IS-Consumer Products'),
('SAP IS-Defense & Security'),
('SAP IS-Retail'),
('SAP IS-Insurance'),
('SAP IS-Mill Products'),
('SAP IS-Higher Education & Research'),
('SAP IS-Industrial Machinery & Components'),
('SAP IS-Logistics Service Providers'),
('SAP IS-Automotive'),
('SAP IS-Chemicals'),
('SAP IS-Pharmaceuticals'),
('SAP IS-Banking'),
('SAP IS-Telecoms'),
('SAP IS-Life Sciences'),
('SAP IS-Mining'),
('SAP IS-Public Sector'),
('SAP IS-Service Provider'),
('SAP IS-Media'),
('SAP IS-Healthcare'),
('SAP IS-Oil & Gas'),
('SAP IS-Utilities'),
('SAP IS-Postal Services')

CREATE TABLE job_skills(
skill_id INT(10) UNSIGNED NOT NULL,
skil_wtg TINYINT(2) UNSIGNED,
skill_type_id INT(10) UNSIGNED NOT NULL,
job_id INT(10) UNSIGNED NOT NULL,
created_by INT(10) UNSIGNED NOT NULL
)

SELECT LAST_INSERT_ID() from job_table;
SELECT Job.job_id, job.job_title,job.start_date,toilUser.f_name
FROM job_table as job
INNER JOIN toilUser
ON job.created_by=toilUser.user_id where toilUser.user_id=5;
