toilUser use toil;
 describe toil;
 CREATE TABLE toilUser(
user_id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
email_id VARCHAR(70) NOT NULL,
f_name VARCHAR(40),
l_name VARCHAR(40),
company VARCHAR(40),
phoneNumber VARCHAR(40),
isActive TINYINT(1) UNSIGNED  NOT NULL DEFAULT 1,
passwd VARCHAR(32) NOT NULL,
isadmin TINYINT(1) UNSIGNED  NOT NULL DEFAULT 1,
admin_id INT(10) UNSIGNED,
CONSTRAINT FK_ADMINID_tbl_toilUser FOREIGN KEY(admin_id)
        REFERENCES toilUser(user_id),
INDEX (email_id(10))
)
select * from toilUser;
 INSERT INTO toilUser (email_id,f_name,l_name,company,phoneNumber,isActive,passwd,isadmin,admin_id) 
 VALUES ('shilpa@yahoo.com','Shilpa','G','adobe','9877876',1,'admin',1,3);
 
 CREATE TABLE job_type(
type_id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
type VARCHAR(40) NOT NULL,
type_desc VARCHAR(150),
INDEX  icat (type(10)),
FULLTEXT fcat (type)
)
select * from job_duration;
INSERT INTO job_type (type,type_desc) 
 VALUES ('Contract','Contract');
 INSERT INTO job_type (type,type_desc)  VALUES ('Permanent','Permanent');
 
 
 --
 CREATE TABLE job_industry(
industry_id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(40) NOT NULL,
INDEX  icat (name(10)),
FULLTEXT fcat (name)
)
INSERT INTO job_industry (name)  VALUES ('Aerospace & Defense'),
('Automotive'),
('Comms & High Tec '),
('Comms & High Tec - Mobile'),
('Comms & High Tec - Web'),
('Consumer Goods - Electrical Equipment'),
('Consumer Goods - Food & Beverage'),
('Consumer Goods - Home & Personal Care'),
('Consumer Goods - Other'),
('Consumer Goods - Tobacco'),
('Financial Services'),
('Healthcare '),
('Industrial Goods '),
('Logistics'),
('Pharmaceuticals'),
('Resources - Farming & Agriculture'),
('Resources - Metals & Minerals'),
('Resources - Mining'),
('Resources - Oil & Gas'),
('Waste Management');

select * from job_table
-----
 CREATE TABLE job_currency(
currency_id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(40) NOT NULL,
INDEX  icat (name(10)),
FULLTEXT fcat (name)
)
INSERT INTO job_currency (name)  VALUES 
('USD - US Dollars'),
('GBP - British Pounds'),
('EUR - Euros'),
('CHF - Swiss Francs'),
('INR - Indian Rupees'),
('AUD - Australian Dollars'),
('AED - UAE Dirhams'),
('HKD - Hong Kong Dollars'),
('CNY - Chinese Yuan Renminbi'),
('RUB - Russian Rubles'),
('JPY - Japanese Yen')
====
CREATE TABLE job_duration(
duration_id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
duration VARCHAR(40) NOT NULL,
INDEX  icat (duration(10)),
FULLTEXT fcat (duration)
)

INSERT INTO job_duration (duration)  VALUES 
('<1 Month'),
('1-2 Months'),
('3-6 Months'),
('7-9 Months'),
('>9 Months')
---
CREATE TABLE language(
language_id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
language VARCHAR(40) NOT NULL,
INDEX  icat (language(10)),
FULLTEXT fcat (language)
)
INSERT INTO language (language)  VALUES 
('English'),
('German'),
('French'),
('Italian'),
('Spanish'),
('Mandarin'),
('Japanese'),
('Dutch'),
('Russian'),
('Hindi'),
('Urdu'),
('Arabic'),
('Portugese'),
('Bengali'),
('Punjabi')
------
CREATE TABLE country(
country_id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
INDEX  icat (name(10)),
FULLTEXT fcat (name)
)
INSERT into country (name) values
('United Kingdom'),
('United States of America'),
('Germany'),
('Switzerland'),
('France'),
('Australia'),
('India'),
('United Arab Emirates'),
('China'),
('Russia'),
('Japan'),
('Afghanistan'),
('Åland Islands (Finland)'),
('Albania'),
('Algeria'),
('American Samoa (USA)'),
('Andorra'),
('Angola'),
('Anguilla (UK)'),
('Antigua and Barbuda'),
('Argentina'),
('Armenia'),
('Aruba (Netherlands)'),
('Australia'),
('Austria'),
('Azerbaijan'),
('Bahamas'),
('Bahrain'),
('Bangladesh'),
('Barbados'),
('Belarus'),
('Belgium'),
('Belize'),
('Benin'),
('Bermuda (UK)'),
('Bhutan'),
('Bolivia'),
('Bosnia and Herzegovina'),
('Botswana'),
('Brazil'),
('British Indian Ocean Territory (UK)'),
('British Virgin Islands (UK)'),
('Brunei'),
('Bulgaria'),
('Burkina Faso'),
('Burundi'),
('Cabo Verde'),
('Cambodia'),
('Cameroon'),
('Canada'),
('Caribbean Netherlands (Netherlands)'),
('Cayman Islands (UK)'),
('Central African Republic'),
('Chad'),
('Chile'),
('China'),
('Christmas Island (Australia)'),
('Cocos (Keeling) Islands (Australia)'),
('Colombia'),
('Comoros'),
('Congo, Republic of the'),
('Congo, Democratic Republic of the'),
('Cook Islands (New Zealand)'),
('Costa Rica'),
('Cote d''Ivoire'),
('Croatia'),
('Cuba'),
('Curaçao (Netherlands)'),
('Cyprus'),
('Czech Republic'),
('Denmark'),
('Djibouti'),
('Dominica'),
('Dominican Republic'),
('Ecuador'),
('Egypt'),
('El Salvador'),
('Equatorial Guinea'),
('Eritrea'),
('Estonia'),
('Ethiopia'),
('Falkland Islands (UK)'),
('Faroe Islands (Denmark)'),
('Fiji'),
('Finland'),
('France'),
('French Guiana (France)'),
('French Polynesia (France)'),
('Gabon'),
('Gambia'),
('Georgia'),
('Germany'),
('Ghana'),
('Gibraltar (UK)'),
('Greece'),
('Greenland (Denmark)'),
('Grenada'),
('Guadeloupe (France)'),
('Guam (USA)'),
('Guatemala'),
('Guernsey (UK)'),
('Guinea'),
('Guinea-Bissau'),
('Guyana'),
('Haiti'),
('Honduras'),
('Hong Kong (China)'),
('Hungary'),
('Iceland'),
('India'),
('Indonesia'),
('International Monetary Fund (IMF)'),
('Iran'),
('Iraq'),
('Ireland'),
('Isle of Man (UK)'),
('Israel'),
('Italy'),
('Jamaica'),
('Japan'),
('Jersey (UK)'),
('Jordan'),
('Kazakhstan'),
('Kenya'),
('Kiribati'),
('Kosovo'),
('Kuwait'),
('Kyrgyzstan'),
('Laos'),
('Latvia'),
('Lebanon'),
('Lesotho'),
('Liberia'),
('Libya'),
('Liechtenstein'),
('Lithuania'),
('Luxembourg'),
('Macau (China)'),
('Macedonia'),
('Madagascar'),
('Malawi'),
('Malaysia'),
('Maldives'),
('Mali'),
('Malta'),
('Marshall Islands'),
('Martinique (France)'),
('Mauritania'),
('Mauritius'),
('Mayotte (France)'),
('Mexico'),
('Micronesia'),
('Moldova'),
('Monaco'),
('Mongolia'),
('Montenegro'),
('Montserrat (UK)'),
('Morocco'),
('Mozambique'),
('Myanmar'),
('Namibia'),
('Nauru'),
('Nepal'),
('Netherlands'),
('New Caledonia (France)'),
('New Zealand'),
('Nicaragua'),
('Niger'),
('Nigeria'),
('Niue (New Zealand)'),
('Norfolk Island (Australia)'),
('North Korea'),
('Northern Mariana Islands (USA)'),
('Norway'),
('Oman'),
('Pakistan'),
('Palau'),
('Palestine'),
('Panama'),
('Papua New Guinea'),
('Paraguay'),
('Peru'),
('Philippines'),
('Pitcairn Islands (UK)'),
('Poland'),
('Portugal'),
('Puerto Rico (USA)'),
('Qatar'),
('Reunion (France)'),
('Romania'),
('Russia'),
('Rwanda'),
('Saint Barthélemy (France)'),
('Saint Helena (UK)'),
('Saint Kitts and Nevis'),
('Saint Lucia'),
('Saint Martin (France)'),
('Saint Pierre and Miquelon (France)'),
('Saint Vincent and the Grenadines'),
('Samoa'),
('San Marino'),
('Sao Tome and Principe'),
('Saudi Arabia'),
('Senegal'),
('Serbia'),
('Seychelles'),
('Sierra Leone'),
('Singapore'),
('Sint Maarten (Netherlands)'),
('Slovakia'),
('Slovenia'),
('Solomon Islands'),
('Somalia'),
('South Africa'),
('South Korea'),
('South Sudan'),
('Spain'),
('Sri Lanka'),
('Sudan'),
('Suriname'),
('Svalbard and Jan Mayen (Norway)'),
('Swaziland'),
('Sweden'),
('Switzerland'),
('Syria'),
('Taiwan'),
('Tajikistan'),
('Tanzania'),
('Thailand'),
('Timor-Leste'),
('Togo'),
('Tokelau (New Zealand)'),
('Tonga'),
('Trinidad and Tobago'),
('Tunisia'),
('Turkey'),
('Turkmenistan'),
('Turks and Caicos Islands (UK)'),
('Tuvalu'),
('Uganda'),
('Ukraine'),
('United Arab Emirates'),
('United Kingdom'),
('United States of America'),
('Uruguay'),
('US Virgin Islands (USA)'),
('Uzbekistan'),
('Vanuatu'),
('Vatican City (Holy See)'),
('Venezuela'),
('Vietnam'),
('Wallis and Futuna Islands (France)'),
('Yemen'),
('Zambia'),
('Zimbabwe')
------------
CREATE TABLE job_table(
job_id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
job_title VARCHAR(250) NOT NULL,
job_type INT(10) UNSIGNED NOT NULL,
job_desc TEXT NOT NULL,
industry_id INT(10) UNSIGNED NOT NULL,
ind_wtg TINYINT(2) UNSIGNED,
salary DECIMAL(10,2),
sal_wtg TINYINT(2) UNSIGNED,
currency_id INT(10) UNSIGNED NOT NULL,
duration_id INT(10) UNSIGNED NOT NULL,
country_id INT(10) UNSIGNED NOT NULL,
country_wtg TINYINT(2) UNSIGNED,
city VARCHAR(100) NOT NULL,
istravel TINYINT(1) UNSIGNED  NOT NULL DEFAULT 1,
trvl_wtg TINYINT(2) UNSIGNED,
lang_id INT(10) UNSIGNED NOT NULL,
lang_wtg TINYINT(2) UNSIGNED,
start_date DATE NOT NULL,
srtdt_wtg TINYINT(2) UNSIGNED,
created_by INT(10) UNSIGNED NOT NULL,
FULLTEXT job_key (job_title)
)
----
 INSERT INTO job_table (job_title,job_type,job_desc,industry_id,ind_wtg,salary,sal_wtg,currency_id,duration_id,
 country_id,country_wtg,city,istravel,trvl_wtg,lang_id,lang_wtg,start_date,srtdt_wtg,created_by)
 VALUES ('Developer',2,'Description hfdgdsfh',2,2,3000,2,2,2,2,1,'London',1,2,2,2,STR_TO_DATE('10/11/2016', '%d/%m/%Y'),2,2);
 INSERT INTO job_table (job_title,job_type,job_desc,industry_id,ind_wtg,salary,sal_wtg,currency_id,duration_id,
 country_id,country_wtg,city,istravel,trvl_wtg,lang_id,lang_wtg,start_date,srtdt_wtg,created_by)
 VALUES ('Developer',2,'Description hfdgdsfh',2,2,3000,2,2,2,2,1,'London',1,2,2,2,'2016-11-30',2,2);
 
 INSERT INTO job_table (job_title,job_type,job_desc,industry_id,ind_wtg,salary,sal_wtg,currency_id,duration_id,country_id,country_wtg,city,istravel,trvl_wtg,lang_id,lang_wtg,start_date,srtdt_wtg,created_by) 
 VALUES('Big data','1','Big dataBig dataBig dataBig databig data','2','2','456','2','3','3','3','3','London','1','1','2','2','2015-12-24','3','3')
 select * from job_table
